export type BuilderFieldKind =
  "text" | "url" | "textarea" | "select" | "checkboxes" | "date" | "file";

export interface BuilderFieldContract {
  id: string;
  label: string;
  kind: BuilderFieldKind;
  placeholder?: string;
  helperText?: string;
  options?: string[];
  optional?: boolean;
}

export interface BuilderContract {
  builderId: string;
  builderName: string;
  purpose: string;
  simpleModeFields: BuilderFieldContract[];
  advancedFields: string[];
  previewType: string;
  requiredFields: string[];
  validationMessages: Record<string, string>;
  primaryActions: string[];
  secondaryActions: string[];
  afterCreatedActions: string[];
  helpHandoffType: string;
  emptyStateCopy: string;
  sampleMockData: Record<string, string | string[]>;
}

const select = (
  id: string,
  label: string,
  options: string[],
): BuilderFieldContract => ({ id, label, kind: "select", options });
const text = (
  id: string,
  label: string,
  placeholder: string,
  optional = false,
): BuilderFieldContract => ({ id, label, kind: "text", placeholder, optional });
const url = (
  id: string,
  label: string,
  placeholder: string,
  optional = false,
): BuilderFieldContract => ({ id, label, kind: "url", placeholder, optional });
const area = (
  id: string,
  label: string,
  placeholder: string,
  optional = false,
): BuilderFieldContract => ({
  id,
  label,
  kind: "textarea",
  placeholder,
  optional,
});
const checks = (
  id: string,
  label: string,
  options: string[],
): BuilderFieldContract => ({ id, label, kind: "checkboxes", options });

export const builderContracts: BuilderContract[] = [
  {
    builderId: "qr-code-builder",
    builderName: "Create QR Code",
    purpose:
      "Make a QR code for a link, form, review page, payment link, menu, booking page, or contact card.",
    simpleModeFields: [
      select("qrType", "What is this QR code for?", [
        "Website / Link",
        "Google Review",
        "Booking Link",
        "Payment Link",
        "Lead Form",
        "Menu",
        "Contact Card",
        "Facebook Page",
        "Instagram Page",
        "Event Signup",
        "Estimate Request",
        "Custom URL",
      ]),
      url(
        "destination",
        "Destination link",
        "Paste the link people should open",
      ),
      text(
        "qrName",
        "QR code name",
        "Example: Free Quote QR, Menu QR, Review QR",
      ),
      text(
        "shortLabel",
        "Short label, optional",
        "Example: Scan to book, Scan for menu, Leave us a review",
        true,
      ),
    ],
    advancedFields: [
      "QR color",
      "Background color",
      "Show logo/initials in preview only",
      "Add to customer/project",
      "Add to campaign/promo",
      "Track scans later placeholder",
      "Export size",
      "Error correction level later placeholder",
    ],
    previewType: "QR preview card",
    requiredFields: ["qrType", "destination", "qrName"],
    validationMessages: {
      destination:
        "Add a destination link so the QR code knows where to send people.",
      qrName: "Name this QR code so you can find it later.",
      contact: "Add at least one contact method for the contact card.",
    },
    primaryActions: ["Test Link", "Create QR Code", "Save Draft"],
    secondaryActions: [],
    afterCreatedActions: ["View QR"],
    helpHandoffType: "QR code setup",
    emptyStateCopy: "Choose a QR type and add its destination to begin.",
    sampleMockData: {
      qrType: "Estimate Request",
      destination: "https://jthomasflooring.example/free-measure",
      qrName: "Free Quote QR",
      shortLabel: "Scan for a free quote",
    },
  },
  {
    builderId: "flyer-builder",
    builderName: "Make a Flyer",
    purpose:
      "Create a flyer for print, social, email, text, Canva, VistaPrint, or customer sharing.",
    simpleModeFields: [
      select("purpose", "Flyer purpose", [
        "Promo",
        "Event",
        "Grand Opening",
        "Free Quote",
        "Special Offer",
        "Class / Program",
        "Menu / Special",
        "Review Request",
        "Business Announcement",
        "Custom",
      ]),
      select("destination", "Where will it be used?", [
        "Facebook",
        "Instagram",
        "Google Business",
        "Print at Home",
        "VistaPrint",
        "Canva",
        "Email/Text Customers",
        "Website/Link Page",
        "Not Sure",
      ]),
      text("headline", "Flyer title / headline", "Spring flooring special"),
      area(
        "message",
        "Main message",
        "Add the main details customers should know",
      ),
      text("offer", "Offer or details", "Free measure with installation"),
      text(
        "dateTime",
        "Date/time, optional",
        "Saturday, May 10 at 10 AM",
        true,
      ),
      text("phone", "Phone", "(401) 555-0142"),
      url("website", "Website or link", "https://example.com", true),
      text("qrCode", "QR code, optional", "Choose a saved QR code", true),
      {
        id: "photo",
        label: "Logo or photo, optional",
        kind: "file",
        optional: true,
      },
      text("cta", "Call-to-action", "Request a free quote"),
    ],
    advancedFields: [
      "Style",
      "Print size",
      "Bleed and safe area",
      "Custom colors",
      "Font settings",
      "Save as template",
    ],
    previewType: "Flyer preview card",
    requiredFields: ["headline"],
    validationMessages: {
      headline: "Add a headline so people know what this flyer is about.",
      contact:
        "Add a phone number, website, or QR code so customers know what to do next.",
      cta: "This flyer may need a QR code or call-to-action.",
    },
    primaryActions: ["Save Draft", "Check Design", "Preview"],
    secondaryActions: [],
    afterCreatedActions: [
      "Download PDF Print",
      "Download PNG",
      "Download JPG",
      "Send to Customers",
      "Post to Social",
      "Add QR Code",
      "Request Start Here Help",
    ],
    helpHandoffType: "Fix my flyer",
    emptyStateCopy: "Add a headline and choose where the flyer will be used.",
    sampleMockData: {
      purpose: "Special Offer",
      destination: "Print at Home",
      headline: "Spring Flooring Special",
      message: "Refresh your room with professional installation.",
      cta: "Request a free measure",
    },
  },
  {
    builderId: "social-post-builder",
    builderName: "Create Post",
    purpose: "Create a Facebook, Instagram, or Google Business post.",
    simpleModeFields: [
      select("postType", "Post type", [
        "Promo",
        "Announcement",
        "Review Request",
        "Event",
        "New Service",
        "Before/After",
        "Daily Special",
        "Membership/Signup",
        "Free Quote",
        "Customer Appreciation",
      ]),
      select("platform", "Destination platform", [
        "Facebook Page",
        "Instagram Business",
        "Google Business Profile",
        "All Connected Accounts",
        "Save Draft Only",
      ]),
      area("caption", "Caption", "What should your audience know?"),
      url("link", "Link or CTA, optional", "https://example.com", true),
      {
        id: "media",
        label: "Attach flyer/image, optional",
        kind: "file",
        optional: true,
      },
      text("qrCode", "QR code, optional", "Choose a saved QR code", true),
      text("hashtags", "Hashtags, optional", "#smallbusiness #local", true),
    ],
    advancedFields: [
      "Schedule settings placeholder",
      "Platform-specific text",
      "Alt text",
      "Save as template",
    ],
    previewType: "Platform post preview",
    requiredFields: ["postType", "platform", "caption"],
    validationMessages: {
      caption: "Add a caption before previewing this post.",
    },
    primaryActions: ["Save Draft", "Copy Caption", "Preview Post"],
    secondaryActions: ["Live posting requires a real connected account."],
    afterCreatedActions: [
      "Download Image",
      "Post Now — placeholder",
      "Schedule Later — placeholder",
      "Send to Customers",
      "Request Start Here Help",
    ],
    helpHandoffType: "Social post help",
    emptyStateCopy: "Choose a platform and write the message for your post.",
    sampleMockData: {
      postType: "Free Quote",
      platform: "Facebook Page",
      caption: "Ready for new floors? Request a free measure today.",
    },
  },
  {
    builderId: "business-card-builder",
    builderName: "Business Cards",
    purpose:
      "Create or prepare a business card layout for print, Canva, VistaPrint, or download.",
    simpleModeFields: [
      select("cardType", "Card type", [
        "General Business Card",
        "Personal Card",
        "Appointment Card",
        "QR Card",
        "Review Card",
        "Loyalty Card",
      ]),
      checks("information", "Information to show", [
        "Business Name",
        "Logo",
        "Name",
        "Title",
        "Phone",
        "Email",
        "Website",
        "Address",
        "Services",
        "Facebook",
        "Instagram",
        "QR Code",
      ]),
      select("qrOption", "QR code option", [
        "No QR",
        "Website QR",
        "Contact Card QR",
        "Booking QR",
        "Review QR",
        "Quote Request QR",
      ]),
      select("destination", "Destination", [
        "Print at Home",
        "VistaPrint",
        "Canva",
        "Download Only",
        "Have Start Here Format It",
      ]),
      select("sides", "Card sides", ["Front only", "Front and back"]),
    ],
    advancedFields: [
      "Card size",
      "Bleed and safe area",
      "Paper notes",
      "Custom colors",
      "Save as template",
    ],
    previewType: "Front/back business card preview",
    requiredFields: ["cardType", "information", "destination"],
    validationMessages: {
      contact: "Add at least one way for customers to contact you.",
    },
    primaryActions: ["Check Print", "Save Draft", "Preview"],
    secondaryActions: [],
    afterCreatedActions: [
      "Download PDF Print",
      "Download PNG Front",
      "Download PNG Back",
      "Request VistaPrint Setup Help",
      "Request Start Here Help",
    ],
    helpHandoffType: "Business card setup",
    emptyStateCopy: "Choose what information belongs on the card.",
    sampleMockData: {
      cardType: "General Business Card",
      information: ["Business Name", "Name", "Phone", "Email", "Website"],
      destination: "VistaPrint",
      sides: "Front and back",
    },
  },
  {
    builderId: "send-promotion-builder",
    builderName: "Send Promotion",
    purpose: "Send or prepare a promotion for selected customer groups.",
    simpleModeFields: [
      select("promotionType", "Promotion type", [
        "Discount",
        "Free Item",
        "Limited-Time Offer",
        "Event Invite",
        "New Service",
        "Review Request",
        "Booking Push",
        "Customer Appreciation",
      ]),
      select("recipients", "Recipient group", [
        "All Customers",
        "Leads",
        "Active Customers",
        "Past Customers",
        "Customers With Unpaid Invoices",
        "Customers Waiting Approval",
        "Customers by Tag",
        "Manually Selected Customers",
      ]),
      text("title", "Message title", "Spring customer special"),
      area("message", "Short message", "Add the promotion details"),
      url("link", "Link or QR", "https://example.com", true),
      {
        id: "expiration",
        label: "Expiration date, optional",
        kind: "date",
        optional: true,
      },
      text("cta", "Call-to-action", "Book now"),
    ],
    advancedFields: [
      "Custom recipient filters",
      "Delivery channel placeholder",
      "Tracking placeholder",
      "Save as template",
    ],
    previewType: "Customer message preview",
    requiredFields: ["promotionType", "recipients", "title", "message"],
    validationMessages: { message: "Add a short promotion message." },
    primaryActions: ["Save Draft", "Copy Message", "Preview Recipients"],
    secondaryActions: [],
    afterCreatedActions: [
      "Send — placeholder",
      "Export Customer List",
      "Create Flyer From This",
      "Create Post From This",
      "Request Help",
    ],
    helpHandoffType: "Promotion help",
    emptyStateCopy: "Choose an offer and the customers who should receive it.",
    sampleMockData: {
      promotionType: "Limited-Time Offer",
      recipients: "Active Customers",
      title: "Spring flooring special",
      message: "Book your free measure this month.",
    },
  },
  {
    builderId: "review-booster-builder",
    builderName: "Review Booster",
    purpose: "Help your business collect more customer reviews.",
    simpleModeFields: [
      select("platform", "Review platform", [
        "Google Review",
        "Facebook Review",
        "Custom Review Link",
      ]),
      url("reviewLink", "Review link", "Paste the review page link"),
      select("customerGroup", "Customer group", [
        "Recently Paid Customers",
        "Completed Jobs",
        "Active Customers",
        "Custom Selected Customers",
      ]),
      area(
        "reviewMessage",
        "Review message",
        "Thank you for choosing us. Could you leave us a quick review? It helps our small business grow.",
      ),
    ],
    advancedFields: [
      "Follow-up timing placeholder",
      "Exclude customer tags",
      "Custom thank-you page",
    ],
    previewType: "Review request preview",
    requiredFields: [
      "platform",
      "reviewLink",
      "customerGroup",
      "reviewMessage",
    ],
    validationMessages: {
      reviewLink: "Add the page where customers should leave their review.",
    },
    primaryActions: ["Create Review QR", "Copy Review Message", "Save Draft"],
    secondaryActions: [],
    afterCreatedActions: [
      "Send to Customers — placeholder",
      "Make Review Card",
      "Make Review Flyer",
      "Request Help",
    ],
    helpHandoffType: "Review booster help",
    emptyStateCopy: "Add your review link and choose a customer group.",
    sampleMockData: {
      platform: "Google Review",
      customerGroup: "Recently Paid Customers",
      reviewMessage:
        "Thank you for choosing us. Could you leave us a quick review? It helps our small business grow.",
    },
  },
  {
    builderId: "lead-form-builder",
    builderName: "Lead Forms",
    purpose: "Create a public lead, quote, booking, or contact form.",
    simpleModeFields: [
      select("formType", "Form type", [
        "Contact Request",
        "Estimate Request",
        "Booking Request",
        "Service Inquiry",
        "Event Signup",
        "Promo Claim",
        "Free Consultation",
        "Cleaning Quote",
        "Gym Trial Class",
        "Restaurant Catering Request",
        "Flooring Estimate Request",
      ]),
      text("formTitle", "Form title", "Request a free estimate"),
      area(
        "description",
        "Form description, optional",
        "Tell customers what happens after they submit.",
        true,
      ),
      checks("fields", "Fields to collect", [
        "Name",
        "Phone",
        "Email",
        "Business Name",
        "Address",
        "Service Needed",
        "Budget",
        "Date Needed",
        "Upload File/Photo",
        "Message",
        "Preferred Contact Method",
        "How Did You Hear About Us?",
      ]),
      area(
        "thankYou",
        "Thank you message",
        "Thank you. We received your request and will contact you soon.",
      ),
    ],
    advancedFields: [
      "Required-field controls",
      "Notifications placeholder",
      "Custom confirmation page",
      "Spam protection placeholder",
    ],
    previewType: "Public form preview",
    requiredFields: ["formType", "formTitle", "fields", "thankYou"],
    validationMessages: {
      fields: "Choose at least one field for customers to complete.",
    },
    primaryActions: ["Save Form", "Preview Form", "Copy Link"],
    secondaryActions: [],
    afterCreatedActions: [
      "Create QR Code",
      "Add to Flyer",
      "Post to Social",
      "View Leads",
    ],
    helpHandoffType: "Lead form setup",
    emptyStateCopy:
      "Choose the type of request and the information to collect.",
    sampleMockData: {
      formType: "Flooring Estimate Request",
      formTitle: "Request a Free Measure",
      fields: ["Name", "Phone", "Email", "Address", "Service Needed"],
      thankYou: "Thank you. We will contact you soon.",
    },
  },
  {
    builderId: "menu-price-sheet-builder",
    builderName: "Menu / Price Sheet",
    purpose: "Create a simple menu, service list, or price sheet.",
    simpleModeFields: [
      text("title", "Title", "Services & Pricing"),
      area("categories", "Categories", "Installation\nRepairs\nMaintenance"),
      area("items", "Items/services", "Hardwood installation"),
      area("descriptions", "Descriptions", "What is included"),
      area("prices", "Prices", "Starting at $..."),
      area("notes", "Notes, optional", "Prices may vary by project.", true),
      text("qrCode", "QR code, optional", "Choose a saved QR code", true),
      text(
        "footer",
        "Footer / call-to-action, optional",
        "Call for a custom quote",
        true,
      ),
    ],
    advancedFields: [
      "Page size",
      "Columns",
      "Brand colors",
      "Item images",
      "Save as template",
    ],
    previewType: "Menu/price sheet document preview",
    requiredFields: ["title", "items"],
    validationMessages: { items: "Add at least one item or service." },
    primaryActions: ["Save Draft", "Check Design", "Preview"],
    secondaryActions: [],
    afterCreatedActions: [
      "Download PDF",
      "Download PNG",
      "Add QR",
      "Request Help",
    ],
    helpHandoffType: "Menu or price sheet help",
    emptyStateCopy: "Add your first category, item, and price.",
    sampleMockData: {
      title: "Flooring Services",
      categories: "Installation",
      items: "Luxury vinyl plank",
      prices: "Free custom estimate",
    },
  },
  {
    builderId: "sign-door-hanger-builder",
    builderName: "Yard Sign / Door Hanger",
    purpose: "Create print-ready signage, yard signs, or door hangers.",
    simpleModeFields: [
      select("signType", "Sign type", [
        "Yard Sign",
        "Door Hanger",
        "Banner",
        "Poster",
        "Window Sign",
        "Counter Sign",
      ]),
      text("headline", "Headline", "Beautiful Floors Start Here"),
      area(
        "message",
        "Short message",
        "Professional installation and free estimates",
      ),
      text("phone", "Phone", "(401) 555-0142"),
      url("link", "Website/link", "https://example.com", true),
      text("qrCode", "QR code", "Choose a saved QR code", true),
      { id: "photo", label: "Logo/photo", kind: "file", optional: true },
      text("cta", "Call-to-action", "Scan for a free quote"),
    ],
    advancedFields: [
      "Print size",
      "Bleed and safe area",
      "Double-sided option",
      "VistaPrint prep",
      "Save as template",
    ],
    previewType: "Print sign preview",
    requiredFields: ["signType", "headline"],
    validationMessages: { contact: "Add a phone, link, or QR code." },
    primaryActions: ["Check Print", "Save Draft", "Preview"],
    secondaryActions: [],
    afterCreatedActions: [
      "Download Print PDF",
      "Download PNG",
      "Request VistaPrint Setup Help",
      "Request Start Here Help",
    ],
    helpHandoffType: "VistaPrint setup",
    emptyStateCopy: "Choose a sign type and add a short, readable headline.",
    sampleMockData: {
      signType: "Yard Sign",
      headline: "Free Flooring Estimates",
      phone: "(401) 555-0142",
      cta: "Scan for a quote",
    },
  },
  {
    builderId: "event-promo-builder",
    builderName: "Event Promo",
    purpose:
      "Create event materials and connect them to signup, posts, and customer sending.",
    simpleModeFields: [
      text("eventTitle", "Event title", "Community Open House"),
      { id: "date", label: "Date", kind: "date" },
      text("time", "Time", "6:00 PM"),
      text("location", "Location", "123 Main Street"),
      text("price", "Price or free", "Free"),
      area("description", "Description", "What should attendees know?"),
      url("signupLink", "Signup link", "https://example.com/signup", true),
      text("qrCode", "QR code", "Choose a saved QR code", true),
      text("contact", "Contact info", "(401) 555-0142"),
    ],
    advancedFields: [
      "Capacity",
      "Reminder settings placeholder",
      "Social destinations",
      "Save as template",
    ],
    previewType: "Event promo preview",
    requiredFields: ["eventTitle", "date", "location"],
    validationMessages: { eventTitle: "Add an event title." },
    primaryActions: ["Save Draft", "Preview", "Check Design"],
    secondaryActions: [],
    afterCreatedActions: [
      "Make Flyer",
      "Create Post",
      "Create QR",
      "Create Lead Form",
      "Send to Customers",
      "Request Help",
    ],
    helpHandoffType: "Event promo help",
    emptyStateCopy: "Add the event name, date, and location.",
    sampleMockData: {
      eventTitle: "Flooring Open House",
      time: "6:00 PM",
      location: "J Thomas Flooring Showroom",
      price: "Free",
    },
  },
  {
    builderId: "fix-something-flow",
    builderName: "Fix Something",
    purpose:
      "Diagnose and fix an uploaded design, file, screenshot, or business material.",
    simpleModeFields: [
      { id: "file", label: "Upload file", kind: "file" },
      select("fixType", "What needs fixed?", [
        "Make it look better",
        "Make it print-ready",
        "Add QR code",
        "Change phone/email/address",
        "Fix blurry logo",
        "Resize for Facebook",
        "Resize for Instagram",
        "Resize for VistaPrint",
        "Fix spacing",
        "Fix colors",
        "Fix wording",
        "Remove something",
        "Add something",
        "I am not sure",
      ]),
      area(
        "notes",
        "Notes",
        "Describe what looks wrong or what should change",
        true,
      ),
    ],
    advancedFields: [
      "File dimensions",
      "Color profile",
      "Print vendor details",
    ],
    previewType: "Uploaded file diagnosis card",
    requiredFields: ["file", "fixType"],
    validationMessages: {
      file: "Upload the file or screenshot you want to fix.",
    },
    primaryActions: ["Check File", "Save Request", "Walk Me Through It"],
    secondaryActions: [],
    afterCreatedActions: [
      "Show DIY Suggestions",
      "Open Guided Checklist",
      "Request Start Here Fix It",
    ],
    helpHandoffType: "Fix my design",
    emptyStateCopy: "Upload the item that needs attention.",
    sampleMockData: {
      fixType: "Make it print-ready",
      notes: "The text looks close to the edge.",
    },
  },
  {
    builderId: "canva-help-flow",
    builderName: "Canva Help",
    purpose: "Prepare or fix Canva designs without sharing a password.",
    simpleModeFields: [
      url(
        "canvaLink",
        "Canva design link, optional",
        "Paste a Canva share link",
        true,
      ),
      {
        id: "screenshot",
        label: "Upload Canva screenshot, optional",
        kind: "file",
        optional: true,
      },
      select("helpType", "What do you need help with?", [
        "Resize",
        "Fix Layout",
        "Add QR",
        "Make Print-Ready",
        "Change Text",
        "Clean Up Design",
        "Not Sure",
      ]),
      area("notes", "Notes", "Describe what you want to change", true),
    ],
    advancedFields: [
      "Target size",
      "Destination platform",
      "Print vendor notes",
    ],
    previewType: "Canva help summary",
    requiredFields: ["helpType"],
    validationMessages: {
      source: "Add a Canva link or screenshot so the design can be reviewed.",
    },
    primaryActions: [
      "Walk Me Through Canva",
      "Prepare Content for Canva",
      "Request Start Here Canva Help",
    ],
    secondaryActions: ["Never share your Canva password."],
    afterCreatedActions: [],
    helpHandoffType: "Canva help",
    emptyStateCopy:
      "Paste a share link or upload a screenshot—never a password.",
    sampleMockData: {
      helpType: "Make Print-Ready",
      notes: "Prepare this flyer for printing.",
    },
  },
  {
    builderId: "vistaprint-print-setup-flow",
    builderName: "VistaPrint / Print Setup Help",
    purpose: "Prepare files correctly for VistaPrint or another print service.",
    simpleModeFields: [
      select("printItem", "What are you printing?", [
        "Business Card",
        "Flyer",
        "Door Hanger",
        "Yard Sign",
        "Banner",
        "Menu",
        "Postcard",
        "Sticker",
        "Other",
      ]),
      { id: "file", label: "Upload design/screenshot", kind: "file" },
      select("issue", "Select issue", [
        "Text Too Close to Edge",
        "Need Correct Size",
        "Need PDF Print File",
        "Need QR Added",
        "Logo Blurry",
        "Not Sure If It Will Print Right",
      ]),
      area("notes", "Notes", "Add any printer instructions or concerns", true),
    ],
    advancedFields: [
      "Exact product size",
      "Bleed amount",
      "Paper/finish notes",
    ],
    previewType: "Print setup checklist",
    requiredFields: ["printItem", "file", "issue"],
    validationMessages: {
      file: "Upload the design or screenshot you want checked.",
    },
    primaryActions: [
      "Check Print Setup",
      "Download Print Checklist",
      "Request Start Here to Format It",
    ],
    secondaryActions: ["Never share your VistaPrint password."],
    afterCreatedActions: [],
    helpHandoffType: "VistaPrint setup",
    emptyStateCopy: "Choose the printed item and upload its design.",
    sampleMockData: {
      printItem: "Business Card",
      issue: "Not Sure If It Will Print Right",
      notes: "Please check the safe area.",
    },
  },
];

const taskBuilderIds: Record<string, string> = {
  "Create QR Code": "qr-code-builder",
  "Make a Flyer": "flyer-builder",
  "Create Post": "social-post-builder",
  "Business Cards": "business-card-builder",
  "Send Promotion": "send-promotion-builder",
  "Review Booster": "review-booster-builder",
  "Lead Forms": "lead-form-builder",
  "Menu / Price Sheet": "menu-price-sheet-builder",
  "Yard Sign": "sign-door-hanger-builder",
  "Door Hanger": "sign-door-hanger-builder",
  "Event Promo": "event-promo-builder",
  "Fix Something": "fix-something-flow",
  "Canva Help": "canva-help-flow",
  "VistaPrint / Print Setup Help": "vistaprint-print-setup-flow",
};

export function getBuilderContract(task?: string) {
  const builderId = task ? taskBuilderIds[task] : undefined;
  return builderContracts.find((contract) => contract.builderId === builderId);
}
