import type {
  GuideResource,
  HelpService,
  HelpServiceQuestion,
  MonthlySupportPlan,
} from "../types/models";

const q = (
  serviceKey: string,
  fieldKey: string,
  questionText: string,
  inputType: HelpServiceQuestion["inputType"],
  options: string[] = [],
  required = false,
  sortOrder = 0,
  helperText?: string,
): HelpServiceQuestion => ({
  id: `${serviceKey}-${fieldKey}`,
  serviceKey,
  fieldKey,
  questionText,
  inputType,
  options,
  required,
  sortOrder,
  helperText,
});

const specificQuestions: Record<string, HelpServiceQuestion[]> = {
  fix_flyer: [
    q(
      "fix_flyer",
      "changes",
      "What do you need fixed?",
      "multiSelect",
      [
        "Make it look better",
        "Change date/time",
        "Change contact information",
        "Add QR code",
        "Resize for social media",
        "Make print-ready",
        "Fix blurry logo",
        "Fix wording",
        "Not sure",
      ],
      true,
      1,
    ),
    q(
      "fix_flyer",
      "destination",
      "Where will this flyer be used?",
      "multiSelect",
      [
        "Facebook",
        "Instagram",
        "Google Business",
        "Print at Home",
        "VistaPrint",
        "Canva",
        "Email/Text",
        "Not sure",
      ],
      true,
      2,
    ),
    q("fix_flyer", "deadline", "Do you have a deadline?", "date", [], false, 3),
    q(
      "fix_flyer",
      "details",
      "Describe what you want changed.",
      "textarea",
      [],
      true,
      4,
    ),
  ],
  business_card_setup: [
    q(
      "business_card_setup",
      "need",
      "What do you need?",
      "select",
      [
        "New business card design",
        "Fix existing card",
        "Prepare for VistaPrint",
        "Add QR code",
        "Change contact information",
        "Create front and back files",
        "Not sure",
      ],
      true,
      1,
    ),
    q(
      "business_card_setup",
      "information",
      "What information should be on the card?",
      "multiSelect",
      [
        "Business name",
        "Logo",
        "Name",
        "Title",
        "Phone",
        "Email",
        "Website",
        "Address",
        "Facebook",
        "Instagram",
        "QR code",
        "Services",
      ],
      true,
      2,
    ),
    q(
      "business_card_setup",
      "existingDesign",
      "Do you already have a design?",
      "select",
      [
        "Yes, uploading it",
        "Yes, I have a Canva link",
        "No, start from my brand kit",
        "Not sure",
      ],
      true,
      3,
    ),
    q(
      "business_card_setup",
      "printDestination",
      "Where will it be printed?",
      "select",
      ["VistaPrint", "Canva", "Local printer", "Download only", "Not sure"],
      true,
      4,
    ),
  ],
  qr_code_setup: [
    q(
      "qr_code_setup",
      "destinationType",
      "What should the QR code open?",
      "select",
      [
        "Website",
        "Booking link",
        "Payment link",
        "Google review",
        "Menu",
        "Signup",
        "Contact card",
        "Lead form",
        "Social page",
        "Custom link",
        "Not sure",
      ],
      true,
      1,
    ),
    q(
      "qr_code_setup",
      "destination",
      "Paste the link if you have it.",
      "link",
      [],
      false,
      2,
    ),
    q(
      "qr_code_setup",
      "usedWhere",
      "Where will the QR code be used?",
      "multiSelect",
      [
        "Flyer",
        "Business card",
        "Sign",
        "Menu",
        "Social post",
        "Website",
        "Estimate/invoice",
        "Not sure",
      ],
      true,
      3,
    ),
    q(
      "qr_code_setup",
      "fileType",
      "What file do you need?",
      "select",
      ["PNG", "PDF sign", "Both", "Add it to an existing design"],
      true,
      4,
    ),
  ],
  canva_help: [
    q(
      "canva_help",
      "need",
      "What do you need help with?",
      "multiSelect",
      [
        "Resize",
        "Fix layout",
        "Add QR",
        "Make print-ready",
        "Change text",
        "Clean up design",
        "Export file",
        "Not sure",
      ],
      true,
      1,
    ),
    q(
      "canva_help",
      "canvaLink",
      "Do you have a Canva share link?",
      "link",
      [],
      false,
      2,
      "Share a Canva link or screenshot. Never share your password.",
    ),
    q(
      "canva_help",
      "designFor",
      "What is the design for?",
      "select",
      ["Flyer", "Business card", "Social post", "Menu", "Sign", "Other"],
      true,
      3,
    ),
    q(
      "canva_help",
      "details",
      "Describe what you need changed.",
      "textarea",
      [],
      true,
      4,
    ),
  ],
  vistaprint_setup: [
    q(
      "vistaprint_setup",
      "printing",
      "What are you printing?",
      "select",
      [
        "Business card",
        "Flyer",
        "Door hanger",
        "Yard sign",
        "Banner",
        "Menu",
        "Postcard",
        "Sticker",
        "Other",
      ],
      true,
      1,
    ),
    q(
      "vistaprint_setup",
      "need",
      "What do you need help with?",
      "multiSelect",
      [
        "Text too close to edge",
        "Need correct size",
        "Need PDF print file",
        "Need QR added",
        "Logo blurry",
        "Not sure if it will print right",
        "Need help uploading/design setup",
      ],
      true,
      2,
    ),
    q(
      "vistaprint_setup",
      "sizeSelected",
      "Do you have the VistaPrint product size selected?",
      "select",
      ["Yes", "No", "Not sure"],
      true,
      3,
    ),
    q("vistaprint_setup", "notes", "Add notes.", "textarea", [], false, 4),
  ],
  logo_cleanup: [
    q(
      "logo_cleanup",
      "need",
      "What do you need?",
      "multiSelect",
      [
        "Clean up blurry logo",
        "Remove background",
        "Create transparent PNG",
        "Create print-ready file",
        "Resize logo",
        "Make social profile version",
        "Create black/white version",
        "Not sure",
      ],
      true,
      1,
    ),
    q(
      "logo_cleanup",
      "use",
      "Where will you use it?",
      "multiSelect",
      [
        "Flyer",
        "Business card",
        "Website",
        "Social profile",
        "Sign",
        "Estimate/invoice header",
        "Other",
      ],
      true,
      2,
    ),
    q(
      "logo_cleanup",
      "details",
      "Describe what needs changed.",
      "textarea",
      [],
      true,
      3,
    ),
  ],
  custom_business_kit: [
    q(
      "custom_business_kit",
      "industry",
      "What kind of business is this?",
      "text",
      [],
      true,
      1,
    ),
    q(
      "custom_business_kit",
      "included",
      "What do you need included?",
      "multiSelect",
      [
        "Brand kit",
        "Item/service bank",
        "Estimate templates",
        "Invoice templates",
        "QR codes",
        "Lead forms",
        "Message templates",
        "Terms/footers",
        "Flyers/posts",
        "Business cards",
        "Print files",
        "Connected account guidance",
        "Not sure",
      ],
      true,
      2,
    ),
    q(
      "custom_business_kit",
      "tools",
      "What tools do you already use?",
      "multiSelect",
      [
        "QuickBooks",
        "Excel/CSV",
        "Canva",
        "Google Drive",
        "Facebook",
        "Instagram",
        "Google Business",
        "Other",
      ],
      false,
      3,
    ),
    q(
      "custom_business_kit",
      "details",
      "What do you want Start Here to set up?",
      "textarea",
      [],
      true,
      4,
    ),
  ],
  document_template_setup: [
    q(
      "document_template_setup",
      "templateType",
      "What do you need set up?",
      "select",
      [
        "Estimate template",
        "Invoice template",
        "Both",
        "Progress invoice template",
        "Change order template",
        "Not sure",
      ],
      true,
      1,
    ),
    q(
      "document_template_setup",
      "industry",
      "What kind of business is this for?",
      "text",
      [],
      true,
      2,
    ),
    q(
      "document_template_setup",
      "customerFields",
      "What should show on the customer document?",
      "multiSelect",
      [
        "Logo",
        "Business info",
        "Customer info",
        "Project/job info",
        "Sections/categories",
        "Quantity",
        "Rate",
        "Total",
        "Notes",
        "Terms",
        "Payment instructions",
        "Footer",
        "QR code",
        "Signature/approval area",
      ],
      true,
      3,
    ),
    q(
      "document_template_setup",
      "internalFields",
      "What should stay internal?",
      "multiSelect",
      [
        "Internal cost",
        "Profit",
        "Markup",
        "Supplier",
        "Internal notes",
        "Hidden columns",
        "Other",
      ],
      true,
      4,
    ),
    q(
      "document_template_setup",
      "approval",
      "Do you need approval settings?",
      "multiSelect",
      [
        "Simple checkbox approval",
        "Typed name",
        "Signature",
        "Request changes",
        "Reject with note",
        "Not sure",
      ],
      false,
      5,
    ),
    q(
      "document_template_setup",
      "saveToKit",
      "Save this into My Business Kit?",
      "toggle",
      [],
      true,
      6,
    ),
  ],
};

const seeds: Array<[string, string, string, string, string]> = [
  [
    "fix_flyer",
    "Fix My Flyer",
    "Clean up, resize, correct, or prepare an existing flyer.",
    "$25+",
    "Design Help",
  ],
  [
    "simple_promo_graphic",
    "Simple Promo Graphic",
    "Prepare a clear graphic for a simple offer or announcement.",
    "$35+",
    "Design Help",
  ],
  [
    "custom_flyer",
    "Custom Flyer / Event Graphic",
    "Build a more detailed flyer or event graphic.",
    "$65+",
    "Design Help",
  ],
  [
    "event_mini_pack",
    "Event Mini Pack",
    "Coordinate a small set of event graphics and files.",
    "$95+",
    "Design Help",
  ],
  [
    "qr_code_setup",
    "QR Code Setup",
    "Create or fix a QR code and verify its destination.",
    "$25+",
    "QR Help",
  ],
  [
    "business_card_files",
    "Business Card Design Files",
    "Prepare reusable front and back card files.",
    "$45+",
    "Print Help",
  ],
  [
    "business_card_setup",
    "Business Card Setup",
    "Create, fix, or prepare business cards for print.",
    "$45+",
    "Print Help",
  ],
  [
    "vistaprint_setup",
    "VistaPrint Setup",
    "Prepare correctly sized, print-safe files.",
    "$35+",
    "VistaPrint Help",
  ],
  [
    "canva_help",
    "Canva Help",
    "Get help through share links, screenshots, and exports—never passwords.",
    "$35+",
    "Canva Help",
  ],
  [
    "logo_cleanup",
    "Logo Cleanup",
    "Clean, resize, or export an existing logo.",
    "$75+",
    "Brand Help",
  ],
  [
    "starter_logo",
    "Starter Logo",
    "Create a simple starter logo package.",
    "$100+",
    "Brand Help",
  ],
  [
    "menu_price_sheet_cleanup",
    "Menu / Price Sheet Cleanup",
    "Improve readability and print readiness.",
    "$75+",
    "Design Help",
  ],
  [
    "business_profile_setup",
    "Business Profile Setup",
    "Organize business information and reusable links.",
    "$65+",
    "Business Kit Help",
  ],
  [
    "booking_payment_link_setup",
    "Booking / Payment Link Setup",
    "Organize booking or payment links and matching QR tools.",
    "$35+",
    "Website / Link Help",
  ],
  [
    "website_refresh",
    "Website Refresh",
    "Review and improve an existing small business website.",
    "$150+",
    "Website / Link Help",
  ],
  [
    "custom_business_kit",
    "Custom Business Kit",
    "Build a reusable setup for this business.",
    "$99+",
    "Business Kit Help",
  ],
  [
    "pro_custom_business_kit",
    "Pro Custom Kit Setup",
    "Create a larger reusable business setup.",
    "$199+",
    "Business Kit Help",
  ],
  [
    "full_business_workshop_setup",
    "Full Business Workshop Setup",
    "Coordinate a full set of business tools and templates.",
    "$399+",
    "Business Kit Help",
  ],
  [
    "document_template_setup",
    "Invoice / Estimate Template Setup",
    "Create reusable document layouts and visibility rules.",
    "$95+",
    "Template Help",
  ],
  [
    "monthly_support",
    "Monthly Support",
    "Request an ongoing support plan for this business.",
    "$49/month",
    "General Help",
  ],
];

export const helpServices: HelpService[] = seeds.map(
  (
    [serviceKey, title, shortDescription, startingPriceText, category],
    sortOrder,
  ) => ({
    id: `service-${serviceKey}`,
    serviceKey,
    title,
    shortDescription,
    longDescription: `${shortDescription} Start Here reviews the request and files first, then confirms the work and price before anything larger begins.`,
    startingPriceText,
    category,
    requiredUploads: [
      "Upload the current file, screenshot, or example when available.",
    ],
    acceptedFileTypes: [
      "Image",
      "PDF",
      "Word file",
      "Canva screenshot",
      "Print screenshot",
    ],
    serviceQuestions: specificQuestions[serviceKey] ?? [
      q(
        serviceKey,
        "details",
        "What do you need help with?",
        "textarea",
        [],
        true,
        1,
      ),
    ],
    whatHappensNext: [
      "Start Here reviews your request.",
      "You receive a quote first if the work is larger than a quick fix.",
      "Final files can be saved back to the correct app area.",
    ],
    relatedAppAreas: ["File Vault", "My Business Kit", "Workshop Library"],
    active: true,
    sortOrder,
  }),
);

export const monthlySupportPlans: MonthlySupportPlan[] = [
  {
    id: "plan-basic",
    planKey: "basic",
    title: "Basic Support",
    monthlyPrice: 49,
    shortDescription: "Occasional help and quick questions.",
    bestFor: "Small businesses needing an occasional second set of hands.",
    includedServices: [
      "Priority help review",
      "Small wording/date/contact edits",
      "QR/link questions",
      "Canva/VistaPrint guidance",
      "1 small fix request per month",
    ],
    limits: ["One small fix request monthly"],
    notIncluded: ["Full redesigns", "Large custom kits", "Ads management"],
    active: true,
    sortOrder: 1,
  },
  {
    id: "plan-pro",
    planKey: "pro",
    title: "Pro Support",
    monthlyPrice: 99,
    shortDescription:
      "Regular help with flyers, QR codes, templates, and setup.",
    bestFor: "Businesses making and updating materials regularly.",
    includedServices: [
      "Priority support",
      "Up to 3 small fixes monthly",
      "Flyer/post cleanup",
      "QR updates",
      "Business kit adjustments",
      "Template tweaks",
    ],
    limits: ["Three small fixes monthly"],
    notIncluded: ["Large redesign packages", "Heavy marketing management"],
    active: true,
    sortOrder: 2,
  },
  {
    id: "plan-partner",
    planKey: "partner",
    title: "Business Partner Support",
    monthlyPrice: 199,
    shortDescription:
      "Ongoing help with setup, materials, and reusable business tools.",
    bestFor: "Businesses that want Start Here involved every month.",
    includedServices: [
      "Higher priority support",
      "Up to 6 small fixes monthly",
      "Business kit management",
      "Template and print prep",
      "Monthly tools checkup",
    ],
    limits: ["Six small fixes monthly"],
    notIncluded: [
      "Large projects without a quote",
      "Printing costs",
      "Paid ad management",
    ],
    active: true,
    sortOrder: 3,
  },
];

const guide = (
  guideKey: string,
  title: string,
  shortDescription: string,
  steps: string[],
  relatedActions: string[],
  relatedHelpServiceKey?: string,
): GuideResource => ({
  id: `guide-${guideKey}`,
  guideKey,
  title,
  shortDescription,
  sections: [
    {
      id: `${guideKey}-overview`,
      title: "What to do",
      body: shortDescription,
      checklist: steps,
    },
    {
      id: `${guideKey}-next`,
      title: "Next step",
      body: "Use the related actions below to continue inside Start Here Helper.",
    },
  ],
  relatedActions,
  relatedHelpServiceKey,
  createdAt: "2026-07-06T12:00:00.000Z",
  updatedAt: "2026-07-06T12:00:00.000Z",
});
export const guideResources: GuideResource[] = [
  guide(
    "getting-started",
    "Getting Started",
    "Set up the basic information and tools your business will reuse.",
    [
      "Set up the business profile",
      "Add logo and links",
      "Apply a starter blueprint if useful",
      "Add a customer or lead",
      "Create the first estimate and QR code",
    ],
    [
      "Continue Setup",
      "Open My Business Kit",
      "Apply Business Kit",
      "Add Customer",
    ],
  ),
  guide(
    "first-estimate",
    "Create Your First Estimate",
    "Build a clear estimate and preview every customer-facing output.",
    [
      "Pick a customer",
      "Choose or create a project",
      "Start blank or use a template",
      "Add sections and saved items",
      "Add notes and terms",
      "Preview customer view and official PDF",
      "Send for approval",
    ],
    [
      "Create Estimate",
      "View Estimate Templates",
      "Request Template Setup Help",
    ],
    "document_template_setup",
  ),
  guide(
    "approvals",
    "Send and Get Approvals",
    "Understand approval links, protected versions, and what happens next.",
    [
      "Send the account-free approval link",
      "Customer approves, rejects, or requests changes",
      "Accepted estimate locks",
      "Create an invoice from approved scope",
    ],
    ["Open Money", "Create Invoice from Accepted Estimate"],
  ),
  guide(
    "make-qr",
    "Make a QR Code",
    "Create a destination-based QR code and test it before use.",
    [
      "Pick QR type",
      "Add destination link",
      "Name it",
      "Test link",
      "Download PNG or PDF",
      "Add to a flyer, card, or sign",
    ],
    ["Create QR Code", "View QR Codes", "Request QR Setup Help"],
    "qr_code_setup",
  ),
  guide(
    "before-print",
    "Before You Print",
    "Check safe area, bleed, logo quality, wording, and QR size.",
    [
      "Check safe area and bleed",
      "Use a clear logo",
      "Keep QR code large enough",
      "Proofread contact information",
      "Export a print PDF",
    ],
    ["Open File Vault", "Request VistaPrint Setup Help"],
    "vistaprint_setup",
  ),
  guide(
    "share-canva",
    "Share a Canva Design",
    "Use a Canva share link, screenshot, or exported file—never a password.",
    [
      "Create a share link",
      "Upload a screenshot if needed",
      "Export the current file",
      "Describe the requested change",
      "Never share account passwords",
    ],
    ["Request Canva Help", "Open File Vault"],
    "canva_help",
  ),
];
